plugins:
  flake8:
    enabled: false
    maxLineLength: 100
  pylint:
    enabled: false
    args: ["--max-line-length=100"]
  mypy:
    enabled: false
  black:
    enabled: false
    line_length: 100
  pylsp_mypy:
    enabled: false
