[config]

[templates.nvim]
input_path = "~/.config/matugen/templates/colors.json"
output_path = "~/.config/matugen/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen-theme.conf"
post_hook = "for s in /tmp/kitty-*; do kitty @ --to \"unix:$s\" load-config; done"

[templates.vim]
input_path = "~/.config/matugen/templates/matugen.vim"
output_path = "~/.vim/colors/matugen.vim"
post_hook = "vim --serverlist 2>/dev/null | while read -r s; do [ -n \"$s\" ] && vim --servername \"$s\" --remote-send '<C-\\><C-N>:colorscheme matugen<CR>'; done"
